# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQb1dNRkxsqPsdd6IAyFSifrv1qK-0xf
"""

from transformers import pipeline

import matplotlib.pyplot as plt

classifier = pipeline("sentiment-analysis")

texts = [

    "The battery is amazing",

    "The screen is bad",

    "The camera is very good"

]

labels = []

for text in texts:

    result = classifier(text)[0]

    print(text, "->", result)



    if result['label'] == 'POSITIVE':

        labels.append("Positive")

    else:

        labels.append("Negative")

positive_count = labels.count("Positive")

negative_count = labels.count("Negative")

plt.figure()

plt.bar(["Positive", "Negative"], [positive_count, negative_count])

plt.title("Sentiment Analysis Results")

plt.xlabel("Sentiment")

plt.ylabel("Count")

plt.show()